[versions]
androidx-junit = "1.1.5"
appcompat = "1.7.0"
browser = "1.8.0"
constraintlayout = "2.1.4"
coreKtx = "1.13.1"
desugar_jdk_libs_nio = "2.0.4"
espressoCore = "3.6.0-rc01"
gradle = "8.6.0-alpha05"
gson = "2.11.0"
junit = "4.13.2"
kotlinreflect = "2.0.0"
kotlinStdlib = "2.0.0"
kotlinxCoroutinesAndroid = "1.8.1"
kspPlugin = "2.0.0-1.0.22"
material = "1.12.0"
preferenceKtx = "1.2.1"
storage = "1.5.5"
kotlin = "2.0.0"

[libraries]
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
browser = { module = "androidx.browser:browser", version.ref = "browser" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
desugar_jdk_libs_nio = { module = "com.android.tools:desugar_jdk_libs_nio", version.ref = "desugar_jdk_libs_nio" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect ", version.ref = "kotlinreflect" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlinStdlib" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
material = { module = "com.google.android.material:material", version.ref = "material" }
preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
storage = { module = "com.anggrayudi:storage", version.ref = "storage" }

[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "kspPlugin" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

